### ISSUE TITLE
bug(testrunner):🐛 cannot open stacktrace

### ISSUE THREAD

**Issue by Crashdummyy** [GustavEikaas/easy-dotnet.nvim#183] opened 2024-12-01 22:05 UTC
Hi there

thanks a lot for this project.
I'm as well trying to get rid of rider and this plugin looks like it would be help a lot with that.

I really like the testrunner view but it looks like I cannot open the stacktrace on a failed test which forces me to still fallback to neotest.

Is there anything I am missing or I configured wrong ?

```stacktrace
E5108: Error executing lua: Vim:E484: Cannot open file byte arrays- Without automatic conversion.at FluentAssertions.Execution.XUnit2TestFramework.Throw(String message)at FluentAssertions.Executi
on.TestFrameworkProvider.Throw(String message)at FluentAssertions.Execution.CollectingAssertionStrategy.ThrowIfAny(IDictionary`2 context)at FluentAssertions.Execution.AssertionScope.Dispose()at F
luentAssertions.Equivalency.EquivalencyValidator.AssertEquality(Comparands comparands, EquivalencyValidationContext context)at FluentAssertions.Equivalency.EquivalencyValidator.AssertEquality(Com
parands comparands, EquivalencyValidationContext context)at FluentAssertions.Primitives.ObjectAssertions`2.BeEquivalentTo[TExpectation](TExpectation expectation, Func`2 config, String because, Ob
ject[] becauseArgs)at FluentAssertions.Primitives.ObjectAssertions`2.BeEquivalentTo[TExpectation](TExpectation expectation, String because, Object[] becauseArgs)at GiteaVersioning.Tests.GiteaClie
ntTests.GetRelease() in /home/crashdummy/coding/GiteaVersioning/tests/GiteaVersio                                                                                                                  
stack traceback:                                                                                                                                                                                   
        [C]: in function 'readfile'                                                                                                                                                                
        ...easy-dotnet.nvim/lua/easy-dotnet/test-runner/keymaps.lua:266: in function 'open_stack_trace'                                                                                            
        ...easy-dotnet.nvim/lua/easy-dotnet/test-runner/keymaps.lua:378: in function 'value'                                                                                                       
        .../easy-dotnet.nvim/lua/easy-dotnet/test-runner/render.lua:240: in function <.../easy-dotnet.nvim/lua/easy-dotnet/test-runner/render.lua:234>
```

**Comment by GustavEikaas** [comment] 2024-12-02 07:41
Issue got closed automatically when I merged my fix. Can you update the plugin and check if the issue is resolved?

**Closed** 2024-12-02 07:41 UTC
Labels: bug
